// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbNtvBTukh2fPGmrl_UOtR-6_gdcFO3hA',
    appId: '1:556207779292:android:8cb6a476294cb8016db319',
    messagingSenderId: '556207779292',
    projectId: 'cs310-group-28',
    storageBucket: 'cs310-group-28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByR4_Y-igH8Jo79tffgV7rzm_iJ6oPqPU',
    appId: '1:556207779292:ios:d450b5a9229268926db319',
    messagingSenderId: '556207779292',
    projectId: 'cs310-group-28',
    storageBucket: 'cs310-group-28.appspot.com',
    androidClientId: '556207779292-39h2nef1l30jq9sk9907ma7vq56jjs9p.apps.googleusercontent.com',
    iosClientId: '556207779292-e72n3ul732flidc2qdeelhgj3l57ch7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.cs310Group28',
  );
}
